server:
  port: 0

spring:
  application:
    name: project-service


  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


user:
  name: Guest

springdoc:
  swagger-ui.path: /swagger