server:
  port: 0
  servlet:
    context-path: /api


spring:
  application:
    name: project-service


  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      settings:
        web-allow-others: true



eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true



user:
  name: Guest

springdoc:
  swagger-ui.path: /swagger